/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION "--prefix=/usr/local/gpac/build --libdir=/usr/local/gpac/build/lib --cxx=CXX"
#define GPAC_HAS_MTIM_NSEC
#define GPAC_CONFIG_LINUX
#define GPAC_HAS_QJS
#define GPAC_HAS_JPEG
#define GPAC_HAS_PNG
#define GPAC_HAS_SOCK_UN
#define GPAC_HAS_LZMA
#define GPAC_HAS_FAAD
#define GPAC_HAS_MAD
#define GPAC_HAS_XVID
#define GPAC_HAS_VORBIS
#define GPAC_HAS_THEORA
#define GPAC_HAS_FFMPEG
#define FFMPEG_ENABLE_VVC
#define GPAC_HAS_LIBA52
#define GPAC_HAS_SSL
#define GPAC_HAS_IPV6
#define GPAC_HAS_POLL
#define GPAC_64_BITS
#define GPAC_HAS_LINUX_DVB
#endif
