/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION ""
#define GPAC_HAS_MTIM_NSEC
#define GPAC_CONFIG_LINUX
#define GPAC_HAS_QJS
#define GPAC_HAS_PNG
#define GPAC_HAS_SOCK_UN
#define GPAC_HAS_VORBIS
#define GPAC_HAS_IPV6
#define GPAC_HAS_POLL
#define GPAC_64_BITS
#define GPAC_HAS_LINUX_DVB
#endif
